language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install -r pip-requires.txt --use-mirrors

before_script:
  - psql -c 'create database mics_test;' -U postgres
  - cp mics/localsettings.py.example mics/localsettings.py
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# command to run tests
script:
  - python manage.py test
  - python manage.py harvest