language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies

install:
  - pip install -r pip-requires.txt --use-mirrors

# command to run tests
script:
  - python manage.py test